### ISSUE TITLE
Problems installing on Mac M1

### ISSUE THREAD

**Issue by michaelschem** [markfink/nest2D#14]
Looks like it might not work on a Mac M1.

The file that the error references doesn't exist.

```
(venv) mschem@mbp cython_tutorial % pip install nest2D
Collecting nest2D
  Using cached nest2D-0.4.5.tar.gz (315 kB)
Building wheels for collected packages: nest2D
  Building wheel for nest2D (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/mschem/test/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py'"'"'; __file__='"'"'/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-wheel-f605kuhw
       cwd: /private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/
  Complete output (57 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is AppleClang 13.0.0.13000029
  -- The CXX compiler identification is AppleClang 13.0.0.13000029
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Boost (missing: Boost_INCLUDE_DIR)
  Call Stack (most recent call first):
    /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
    /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindBoost.cmake:2375 (find_package_handle_standard_args)
    CMakeLists.txt:8 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/build/temp.macosx-10.14-arm64-3.8/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/build/temp.macosx-10.14-arm64-3.8/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py", line 69, in <module>
      setup(
    File "/Users/mschem/test/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/mschem/test/venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py", line 42, in run
      self.build_extension(ext)
    File "/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py", line 66, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/build/lib.macosx-10.14-arm64-3.8', '-DPYTHON_EXECUTABLE=/Users/mschem/test/venv/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for nest2D
  Running setup.py clean for nest2D
Failed to build nest2D
Installing collected packages: nest2D
    Running setup.py install for nest2D ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/mschem/test/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py'"'"'; __file__='"'"'/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-record-x362posw/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mschem/test/venv/include/site/python3.8/nest2D
         cwd: /private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/
    Complete output (59 lines):
    running install
    running build
    running build_ext
    -- The C compiler identification is AppleClang 13.0.0.13000029
    -- The CXX compiler identification is AppleClang 13.0.0.13000029
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find Boost (missing: Boost_INCLUDE_DIR)
    Call Stack (most recent call first):
      /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
      /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindBoost.cmake:2375 (find_package_handle_standard_args)
      CMakeLists.txt:8 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/build/temp.macosx-10.14-arm64-3.8/CMakeFiles/CMakeOutput.log".
    See also "/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/build/temp.macosx-10.14-arm64-3.8/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py", line 69, in <module>
        setup(
      File "/Users/mschem/test/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/mschem/test/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 561, in run
        self.run_command('build')
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py", line 42, in run
        self.build_extension(ext)
      File "/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py", line 66, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/build/lib.macosx-10.14-arm64-3.8', '-DPYTHON_EXECUTABLE=/Users/mschem/test/venv/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/mschem/test/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py'"'"'; __file__='"'"'/private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-install-tw7tw4ng/nest2d_90a0bb25a04c42949c4f96fb6576c947/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/48/_sj4kz4d2qn3xdqrkln2gfmc0000gn/T/pip-record-x362posw/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mschem/test/venv/include/site/python3.8/nest2D Check the logs for full command output.
WARNING: You are using pip version 21.1.2; however, version 22.2 is available.
You should consider upgrading via the '/Users/mschem/test/venv/bin/python -m pip install --upgrade pip' command.

```

**Comment by michaelschem** [comment]
Actually tried this on a ubuntu x86 box and got the same issue.

```
Collecting nest2D
  Downloading nest2D-0.4.5.tar.gz (315 kB)
     |████████████████████████████████| 315 kB 5.7 MB/s
Building wheels for collected packages: nest2D
  Building wheel for nest2D (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-quzdjfu2/nest2D/setup.py'"'"'; __file__='"'"'/tmp/pip-install-quzdjfu2/nest2D/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-evg_wpx0
       cwd: /tmp/pip-install-quzdjfu2/nest2D/
  Complete output (45 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "/tmp/pip-install-quzdjfu2/nest2D/setup.py", line 31, in run
      out = subprocess.check_output(['cmake', '--version'])
    File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.8/subprocess.py", line 493, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-quzdjfu2/nest2D/setup.py", line 69, in <module>
      setup(
    File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-quzdjfu2/nest2D/setup.py", line 33, in run
      raise RuntimeError("CMake must be installed to build the following extensions: " +
  RuntimeError: CMake must be installed to build the following extensions: nest2D
  ----------------------------------------
  ERROR: Failed building wheel for nest2D
  Running setup.py clean for nest2D
Failed to build nest2D
Installing collected packages: nest2D
    Running setup.py install for nest2D ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-quzdjfu2/nest2D/setup.py'"'"'; __file__='"'"'/tmp/pip-install-quzdjfu2/nest2D/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zjiw6yyj/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mike/.local/include/python3.8/nest2D
         cwd: /tmp/pip-install-quzdjfu2/nest2D/
    Complete output (49 lines):
    running install
    /usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_ext
    Traceback (most recent call last):
      File "/tmp/pip-install-quzdjfu2/nest2D/setup.py", line 31, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.8/subprocess.py", line 493, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-quzdjfu2/nest2D/setup.py", line 69, in <module>
        setup(
      File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-quzdjfu2/nest2D/setup.py", line 33, in run
        raise RuntimeError("CMake must be installed to build the following extensions: " +
    RuntimeError: CMake must be installed to build the following extensions: nest2D
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-quzdjfu2/nest2D/setup.py'"'"'; __file__='"'"'/tmp/pip-install-quzdjfu2/nest2D/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zjiw6yyj/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mike/.local/include/python3.8/nest2D Check the logs for full command output.
```

**Comment by michaelschem** [comment]
I was missing dependancies

```
sudo apt install libboost-dev libpolyclipping-dev libnlopt-cxx-dev
```
