### ISSUE TITLE
Can NOT use the package in Windows

### ISSUE THREAD

**Issue by YazdanArman** [markfink/nest2D#16]
using command 
`pip install nest2D`

result the following error and package failed to install:
```
Collecting nest2D
  Using cached nest2D-0.4.5.tar.gz (315 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lenovo\AppData\Local\Temp\pip-install-usqm7vdy\nest2d_89c0159e4ea34441a66acba5c31ca1d7\setup.py", line 16, in <module>
          long_description = pypandoc.convert('README.md', format='md', to='rst')
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
here it is clear that the error related to newer version of `pypandoc` lib that has no attribute 'convert'. So I managed to downgrade that package to a version that supports `pypandoc.convert` but again I've got error while installing nest2D and this the error:

```
Collecting nest2D
  Using cached nest2D-0.4.5.tar.gz (315 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: nest2D
  Building wheel for nest2D (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      C:\Users\lenovo\AppData\Local\Temp\pip-install-lh7og82m\nest2d_988a6816a9fe4f33afacbd61024d21df\setup.py:16: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
        long_description = pypandoc.convert('README.md', format='md', to='rst')
      running bdist_wheel
      running build
      running build_ext
      C:\Users\lenovo\AppData\Local\Temp\pip-install-lh7og82m\nest2d_988a6816a9fe4f33afacbd61024d21df\setup.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        cmake_version = LooseVersion(re.search(r'version\s*([\d.]+)', out.decode()).group(1))
      -- Building for: Visual Studio 16 2019
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
      -- The C compiler identification is MSVC 19.29.30136.0
      -- The CXX compiler identification is MSVC 19.29.30136.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find Boost (missing: Boost_INCLUDE_DIR)
      Call Stack (most recent call first):
        C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
        CMakeLists.txt:8 (find_package)


      -- Configuring incomplete, errors occurred!
      See also "C:/Users/lenovo/AppData/Local/Temp/pip-install-lh7og82m/nest2d_988a6816a9fe4f33afacbd61024d21df/build/temp.win-amd64-cpython-39/Release/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lenovo\AppData\Local\Temp\pip-install-lh7og82m\nest2d_988a6816a9fe4f33afacbd61024d21df\setup.py", line 69, in <module>
          setup(
        File "C:\Program Files\Python39\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\Program Files\Python39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\Users\lenovo\AppData\Local\Temp\pip-install-lh7og82m\nest2d_988a6816a9fe4f33afacbd61024d21df\setup.py", line 42, in run
          self.build_extension(ext)
        File "C:\Users\lenovo\AppData\Local\Temp\pip-install-lh7og82m\nest2d_988a6816a9fe4f33afacbd61024d21df\setup.py", line 66, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "C:\Program Files\Python39\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-lh7og82m\\nest2d_988a6816a9fe4f33afacbd61024d21df', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-lh7og82m\\nest2d_988a6816a9fe4f33afacbd61024d21df\\build\\lib.win-amd64-cpython-39', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Python39\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-lh7og82m\\nest2d_988a6816a9fe4f33afacbd61024d21df\\build\\lib.win-amd64-cpython-39', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nest2D
  Running setup.py clean for nest2D
Failed to build nest2D
Installing collected packages: nest2D
  Running setup.py install for nest2D ... error
  error: subprocess-exited-with-error

  × Running setup.py install for nest2D did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      C:\Users\lenovo\AppData\Local\Temp\pip-install-lh7og82m\nest2d_988a6816a9fe4f33afacbd61024d21df\setup.py:16: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
        long_description = pypandoc.convert('README.md', format='md', to='rst')
      running install
      C:\Program Files\Python39\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      C:\Users\lenovo\AppData\Local\Temp\pip-install-lh7og82m\nest2d_988a6816a9fe4f33afacbd61024d21df\setup.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        cmake_version = LooseVersion(re.search(r'version\s*([\d.]+)', out.decode()).group(1))
      -- Building for: Visual Studio 16 2019
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
      -- The C compiler identification is MSVC 19.29.30136.0
      -- The CXX compiler identification is MSVC 19.29.30136.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find Boost (missing: Boost_INCLUDE_DIR)
      Call Stack (most recent call first):
        C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
        CMakeLists.txt:8 (find_package)


      -- Configuring incomplete, errors occurred!
      See also "C:/Users/lenovo/AppData/Local/Temp/pip-install-lh7og82m/nest2d_988a6816a9fe4f33afacbd61024d21df/build/temp.win-amd64-cpython-39/Release/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lenovo\AppData\Local\Temp\pip-install-lh7og82m\nest2d_988a6816a9fe4f33afacbd61024d21df\setup.py", line 69, in <module>
          setup(
        File "C:\Program Files\Python39\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\Program Files\Python39\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\Users\lenovo\AppData\Local\Temp\pip-install-lh7og82m\nest2d_988a6816a9fe4f33afacbd61024d21df\setup.py", line 42, in run
          self.build_extension(ext)
        File "C:\Users\lenovo\AppData\Local\Temp\pip-install-lh7og82m\nest2d_988a6816a9fe4f33afacbd61024d21df\setup.py", line 66, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "C:\Program Files\Python39\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-lh7og82m\\nest2d_988a6816a9fe4f33afacbd61024d21df', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-lh7og82m\\nest2d_988a6816a9fe4f33afacbd61024d21df\\build\\lib.win-amd64-cpython-39', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Python39\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-lh7og82m\\nest2d_988a6816a9fe4f33afacbd61024d21df\\build\\lib.win-amd64-cpython-39', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> nest2D

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by hadikena** [comment]
has this been resolved?

**Comment by CEXT-Dan** [comment]
Same error here

**Comment by shirishd27** [comment]
Same error , is there anything via we can able to  operate this library(nest2D) in python
