### ISSUE TITLE
Install error on  mac m1

### ISSUE THREAD

**Issue by emmajane1313** [markfink/nest2D#17]
Getting this error on install. Mac M1.

I have tried downgrading my pypandoc version to as low as 1.2 as it seems that `convert()` has been depreciated above version 1.7 and now only `convert_text()` or ``convert_file()` work. 

Does anyone know a quick fix/workaround?

```
Collecting nest2D
  Using cached nest2D-0.4.5.tar.gz (315 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: nest2D
  Building wheel for nest2D (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      /private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/setup.py:16: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
        long_description = pypandoc.convert('README.md', format='md', to='rst')
      See http://johnmacfarlane.net/pandoc/installing.html
      for installation options
      ---------------------------------------------------------------

      running bdist_wheel
      running build
      running build_ext
      -- The C compiler identification is AppleClang 14.0.0.14000029
      -- The CXX compiler identification is AppleClang 14.0.0.14000029
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at /opt/homebrew/Cellar/cmake/3.24.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find Boost (missing: Boost_INCLUDE_DIR)
      Call Stack (most recent call first):
        /opt/homebrew/Cellar/cmake/3.24.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        /opt/homebrew/Cellar/cmake/3.24.1/share/cmake/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
        CMakeLists.txt:8 (find_package)


      -- Configuring incomplete, errors occurred!
      See also "/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/build/temp.macosx-12.3-arm64-cpython-310/CMakeFiles/CMakeOutput.log".
      See also "/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/build/temp.macosx-12.3-arm64-cpython-310/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/setup.py", line 69, in <module>
          setup(
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/setup.py", line 42, in run
          self.build_extension(ext)
        File "/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/setup.py", line 66, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/build/lib.macosx-12.3-arm64-cpython-310', '-DPYTHON_EXECUTABLE=/Users/devdesign/.asdf/installs/python/3.10.6/bin/python3.10', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nest2D
  Running setup.py clean for nest2D
Failed to build nest2D
Installing collected packages: nest2D
  Running setup.py install for nest2D ... error
  error: subprocess-exited-with-error

  × Running setup.py install for nest2D did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      /private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/setup.py:16: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
        long_description = pypandoc.convert('README.md', format='md', to='rst')
      See http://johnmacfarlane.net/pandoc/installing.html
      for installation options
      ---------------------------------------------------------------

      running install
      /Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      -- The C compiler identification is AppleClang 14.0.0.14000029
      -- The CXX compiler identification is AppleClang 14.0.0.14000029
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at /opt/homebrew/Cellar/cmake/3.24.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find Boost (missing: Boost_INCLUDE_DIR)
      Call Stack (most recent call first):
        /opt/homebrew/Cellar/cmake/3.24.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        /opt/homebrew/Cellar/cmake/3.24.1/share/cmake/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
        CMakeLists.txt:8 (find_package)


      -- Configuring incomplete, errors occurred!
      See also "/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/build/temp.macosx-12.3-arm64-cpython-310/CMakeFiles/CMakeOutput.log".
      See also "/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/build/temp.macosx-12.3-arm64-cpython-310/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/setup.py", line 69, in <module>
          setup(
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/setup.py", line 42, in run
          self.build_extension(ext)
        File "/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/setup.py", line 66, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/4j/klnj7chj1f5683lz4zj8trd40000gn/T/pip-install-ly0ou68a/nest2d_6e9e9cba06cc44abb4fe4f04b83b061a/build/lib.macosx-12.3-arm64-cpython-310', '-DPYTHON_EXECUTABLE=/Users/devdesign/.asdf/installs/python/3.10.6/bin/python3.10', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> nest2D
```

**Comment by emmajane1313** [comment]
I solved this on my fork of the repo here, check the readme for install instructions:
https://github.com/emmajane1313/nest2D/

**Comment by emmajane1313** [comment]
hey! did you install all of the dependencies first? can you take a screenshot of the error + give any other details of your environment set up

**Comment by emmajane1313** [comment]
also, did you try with `sudo` ?

**Comment by CodinSegal** [comment]
Hey I tried with your git and still got an error. This is the cmd i used to install : `arch -x86_64  -arm64e pip install git+https://github.com/emmajane1313/nest2D.git@download-dependencies --no-cache`
