### ISSUE TITLE
Error while installing nest2D with pip3 install nest2D

### ISSUE THREAD

**Issue by aman-17** [markfink/nest2D#6]
Hey there, I'm using Linux and when try to install it by *pip3 install nest2D* it gives me the below error

Defaulting to user installation because normal site-packages is not writeable
Collecting nest2D
  Using cached nest2D-0.4.5.tar.gz (315 kB)
Building wheels for collected packages: nest2D
  Building wheel for nest2D (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d14338fw/nest2d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d14338fw/nest2d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6y1uy_mu
       cwd: /tmp/pip-install-d14338fw/nest2d/
  Complete output (78 lines):
  /tmp/pip-install-d14338fw/nest2d/setup.py:16: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
    long_description = pypandoc.convert('README.md', format='md', to='rst')
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 10.2.0
  -- The CXX compiler identification is GNU 10.2.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0")
  -- Found PythonInterp: /usr/bin/python3 (found version "3.8.6")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- pybind11 v2.4.dev4
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
    NLopt library cannot be found.  Consider set NLopt_PATH environment
    variable (missing: NLopt_INCLUDE_DIRS)
  Call Stack (most recent call first):
    /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
    lib/libnest2d/cmake_modules/FindNLopt.cmake:62 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    lib/libnest2d/cmake_modules/RequirePackage.cmake:252 (find_package)
    lib/libnest2d/include/libnest2d/optimizers/nlopt/CMakeLists.txt:3 (require_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-d14338fw/nest2d/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-d14338fw/nest2d/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-d14338fw/nest2d/setup.py", line 69, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-d14338fw/nest2d/setup.py", line 42, in run
      self.build_extension(ext)
    File "/tmp/pip-install-d14338fw/nest2d/setup.py", line 66, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-d14338fw/nest2d', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-d14338fw/nest2d/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for nest2D
  Running setup.py clean for nest2D
Failed to build nest2D
Installing collected packages: nest2D
    Running setup.py install for nest2D ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d14338fw/nest2d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d14338fw/nest2d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zi_zzeu_/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/aman17/.local/include/python3.8/nest2D
         cwd: /tmp/pip-install-d14338fw/nest2d/
    Complete output (80 lines):
    /tmp/pip-install-d14338fw/nest2d/setup.py:16: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
      long_description = pypandoc.convert('README.md', format='md', to='rst')
    running install
    running build
    running build_ext
    -- The C compiler identification is GNU 10.2.0
    -- The CXX compiler identification is GNU 10.2.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0")
    -- Found PythonInterp: /usr/bin/python3 (found version "3.8.6")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.4.dev4
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
      NLopt library cannot be found.  Consider set NLopt_PATH environment
      variable (missing: NLopt_INCLUDE_DIRS)
    Call Stack (most recent call first):
      /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
      lib/libnest2d/cmake_modules/FindNLopt.cmake:62 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      lib/libnest2d/cmake_modules/RequirePackage.cmake:252 (find_package)
      lib/libnest2d/include/libnest2d/optimizers/nlopt/CMakeLists.txt:3 (require_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-d14338fw/nest2d/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-d14338fw/nest2d/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d14338fw/nest2d/setup.py", line 69, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-d14338fw/nest2d/setup.py", line 42, in run
        self.build_extension(ext)
      File "/tmp/pip-install-d14338fw/nest2d/setup.py", line 66, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-d14338fw/nest2d', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-d14338fw/nest2d/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d14338fw/nest2d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d14338fw/nest2d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zi_zzeu_/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/aman17/.local/include/python3.8/nest2D Check the logs for full command output.

**Comment by Jordan0990** [comment]
hi aman-17 i have the same problem could you solve it?

**Comment by aman-17** [comment]
> hi aman-17 i have the same problem could you solve it?

I have used other package instead of nest2D
Search for “maxrect” on github, clone it. I feel it is not as complicated as nest2D

**Comment by Jordan0990** [comment]
@aman-17 thank you very much.

**Comment by derekcbr** [comment]
Also can not install on Windows. It shows building wheel for nest2d(setup.py) ... error

**Comment by shirishd27** [comment]
> > hi aman-17 i have the same problem could you solve it?
> 
> I have used other package instead of nest2D Search for “maxrect” on github, clone it. I feel it is not as complicated as nest2D

can we use maxrect for nesting multiple shapes into a one rectangle.

**Comment by aman-17** [comment]
I am not sure but I guess we can use maxrect for nesting multiple shapes into a one rectangle.. The problem with nest2d not getting installed is because of python version. Nest2d can be installed on python3.6 or lower I guess. Its been long time I am not 100% sure about nest3d supporting python versions.

**Comment by shirishd27** [comment]
but in maxrect can we also nest irregular shapes?

**Comment by aman-17** [comment]
Yes you can, you can check this out: https://github.com/planetlabs/maxrect

**Comment by shirishd27** [comment]
if i want to contact you, how can i connect with you?

**Comment by aman-17** [comment]
Email/linkedInEmail: ***@***.***: https://www.linkedin.com/in/amanrangapur/Aman RangapurOn Jul 23, 2024, at 1:22 AM, shirish dwivedi ***@***.***> wrote:﻿
if i want to contact you, how can i connect with you?

**Comment by balcklive** [comment]
> if i want to contact you, how can i connect with you?

have you guys fix this problem? or just to switch a package?

**Comment by aman-17** [comment]
Hello @balcklive use python 3.6
